project_id = "jevcgtpkartfvixnauhg"

[functions.send-daily-reminders]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false

[functions.admin-update-user-role]
verify_jwt = false

[functions.admin-update-user-suspension]
verify_jwt = false